export const GETPRODUCTS_SUCCESS = "GETPRODUCTS_SUCCESS";
export const GETPRODUCTS_LOADING = "GETPRODUCTS_SUCCESS_LOADING";
export const GETPRODUCTS_ERROR = "GETPRODUCTS_SUCCESS_ERROR";

export const GETCATEGORIES_SUCCESS = "GETCATEGORIES_SUCCESS";
export const GETCATEGORIES_LOADING = "GETCATEGORIES_SUCCESS_LOADING";
export const GETCATEGORIES_ERROR = "GETCATEGORIES_SUCCESS_ERROR";
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
